stages:
    - prepare
    - build
    - test

cache:
    key: "$CI_JOB_NAME"
    paths:
        - target/

.prepare-rust-image: &prepare-rust-image
    stage: prepare
    tags:
        - docker

    script:
        - JOB_NAME=( $CI_JOB_NAME )
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - sed -i "0,/FROM /{s/:.*/:${JOB_NAME[3]}/}" Dockerfile.build
        - docker pull "$(grep '^FROM' Dockerfile.build | awk '{ print $2; }' | head -n1)"
        - docker build -t "${CI_REGISTRY_IMAGE}/build:${JOB_NAME[3]}" -f Dockerfile.build .
        - |
            for i in 1 2 3 4 5; do
                docker push "${CI_REGISTRY_IMAGE}/build:${JOB_NAME[3]}" && break || sleep 1
            done
prepare rust image stable: *prepare-rust-image
prepare rust image beta: *prepare-rust-image
prepare rust image nightly: *prepare-rust-image

rustfmt:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:stable"
    script:
        - cargo fmt -- --write-mode diff

build dynamic binary on stable:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:stable"
    script:
        - cargo build --verbose
    cache:
        key: "dynamic binary on stable"
        paths:
            - target/
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock

build dynamic binary on beta:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:beta"
    script:
        - cargo build --verbose
    cache:
        key: "dynamic binary on beta"
        paths:
            - target/
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock

build dynamic binary on nightly:
    stage: build
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:nightly"
    script:
        - cargo build --verbose
    cache:
        key: "dynamic binary on nightly"
        paths:
            - target/
    allow_failure: true
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock

build static binary:
    stage: build
    tags:
        - rust-cross
        - local
    script:
        - cross build --target x86_64-unknown-linux-musl --release
        - cp target/x86_64-unknown-linux-musl/release/i3nator i3nator
    cache:
        key: "static binary"
        paths:
            - target/
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Cargo.toml
            - Cargo.lock
            - i3nator

test dynamic binary on stable:
    stage: test
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:stable"
    dependencies: []
    script:
        - cargo test -- --nocapture
        - cargo test -j1 --features sequential-tests -- --test-threads 1 --nocapture
    cache:
        key: "dynamic binary on stable"
        paths:
            - target/

test dynamic binary on beta:
    stage: test
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:beta"
    dependencies: []
    script:
        - cargo test -- --nocapture
        - cargo test -j1 --features sequential-tests -- --test-threads 1 --nocapture
    cache:
        key: "dynamic binary on beta"
        paths:
            - target/

test dynamic binary on nightly:
    stage: test
    tags:
        - docker
    image: "${CI_REGISTRY_IMAGE}/build:nightly"
    dependencies: []
    script:
        - cargo test -- --nocapture
        - cargo test -j1 --features sequential-tests -- --test-threads 1 --nocapture
    cache:
        key: "dynamic binary on nightly"
        paths:
            - target/
    allow_failure: true

test static binary:
    stage: test
    tags:
        - rust-cross
        - local
    dependencies: []
    script:
        - cross test --target x86_64-unknown-linux-musl -- --nocapture
        - cross test --target x86_64-unknown-linux-musl -j1 --features sequential-tests -- --test-threads 1 --nocapture
    cache:
        key: "static binary"
        paths:
            - target/
